name: simple_auth
description: "SimpleAuth is a Flutter-based app that ensures top-notch security by requiring biometric or facial recognition every time the user returns to the app. It features a Splash Screen, Login and Registration forms, and a Profile Page. The primary focus is on seamless, secure access with mandatory re-authentication to protect user data."

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^9.1.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  provider: ^6.1.2
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  share_plus: ^10.0.2
  device_info_plus: ^10.1.2
  root_jailbreak_detector: ^0.5.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/flags/
    - assets/l10n/
